version: "3.9"
services:
  smerac:
    image: ghcr.io/aleksasiriski/smerac:latest
    environment:
      - TZ=Europe/Berlin
      - UNIDENTIFIED_HOURS=${UNIDENTIFIED_HOURS:-1}
      - CALENDAR_HOURS=${CALENDAR_HOURS:-3}
      - SAVED_PLOTS=${SAVED_PLOTS:-/config/savedplots}
      - DISCORD_TOKEN=${DISCORD_TOKEN:-changeme}
      - NUMBER_OF_ROLES=${NUMBER_OF_ROLES:-2}
      - ROLE_1=${ROLE_1:-IT}
      - ROLE_2=${ROLE_2:-RN}
      - CALENDAR_URL_IT=${CALENDAR_URL:-https://clients6.google.com/calendar/v3/calendars/g3khre7jrsih1idp5b5ahgm1f8@group.calendar.google.com/events?calendarId=g3khre7jrsih1idp5b5ahgm1f8%40group.calendar.google.com&singleEvents=true&timeZone=Europe%2FBelgrade&maxAttendees=1&maxResults=250&sanitizeHtml=true&timeMin=2022-10-23T00%3A00%3A00%2B02%3A00&timeMax=2022-11-30T00%3A00%3A00%2B02%3A00&key=AIzaSyBNlYH01_9Hc5S1J9vuFmu2nUqBZJNAXxs}
      - CALENDAR_URL_RN=${CALENDAR_URL:-https://clients6.google.com/calendar/v3/calendars/dkkfm5u41nijcqnfcpai4tvko4@group.calendar.google.com/events?calendarId=dkkfm5u41nijcqnfcpai4tvko4%40group.calendar.google.com&singleEvents=true&timeZone=Europe%2FBelgrade&maxAttendees=1&maxResults=250&sanitizeHtml=true&timeMin=2022-10-23T00%3A00%3A00%2B02%3A00&timeMax=2022-11-30T00%3A00%3A00%2B02%3A00&key=AIzaSyBNlYH01_9Hc5S1J9vuFmu2nUqBZJNAXxs}
    volumes:
      - smerac-conf:/config:Z
    restart: always
volumes:
  smerac-conf: